services:
  openfisca-aotearoa:
    image: python:3.10
    container_name: openfisca_aotearoa_dev
    working_dir: /openfisca
    restart: always
    command: >
      bash -c "git config --global core.filemode false && 
            git config --global core.autocrlf true && 
            cd /openfisca && 
            pip install --upgrade pip && 
            pip install -e .[dev] --use-deprecated=legacy-resolver &&
            tail -f /dev/null"
    ports:
    - '5000:5000'
    volumes:
    - ../:/openfisca