name: Python

on:
  push:
    branches: [main]
  pull_request:
    types: [assigned, opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Cache tests
        uses: actions/cache@v3
        with:
          path: |
            Makefile
            openfisca_aotearoa/tests
            poetry.lock
            tox.ini
          key: tests-${{ github.sha }}

      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ hashFiles('poetry.lock') }}-${{ github.sha }}

      - name: Build package
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: poetry build

  lint:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: make install

      - name: Lint files
        run: make lint

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Install Tox
        run: pipx install tox

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Restore tests
        uses: actions/cache@v3
        with:
          path: |
            Makefile
            openfisca_aotearoa/tests
            poetry.lock
            tox.ini
          key: tests-${{ github.sha }}

      - name: Restore build
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ hashFiles('poetry.lock') }}-${{ github.sha }}

      - name: Run the test suite
        run: tox
