name: Python

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.13
      - name: Install OpenFisca-Aotearoa
        run: make install
      - name: Run tests
        run: make test
  pythonlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade flake8
      - run: flake8
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade yamllint
      - run: yamllint --version
      - name: YAML lint
        run: yamllint --format=github .
